### PR TITLE
fix: parse

### PR DESCRIPTION
**Pull request by WHYTEWYLL**
It will require a full refresh

### CODE REVIEW

**Comment by forgxyz** [comment]
Looks like something is changing w the events data

```sql
select * from flow_dev.silver.streamline_events
where tx_id = 'be149a67c2000b2d52b32a980b689244086c8f4d7400cc1b0679477e618ad851'
and block_height = 60516643
order by event_index;
```

```json
{
  "from": 2178749115121280800,
  "id": 140213180222734340
}
```

vs prod

```json
{
  "from": "0x1e3c78c6d580273b",
  "id": "140213180222734337"
}
```

**Comment by WHYTEWYLL** [comment]
All good on the last month of data, compare to prod

**Comment by forgxyz** [comment]
LGTM

**Review by forgxyz — APPROVED** [review]

**Review by forgxyz — CHANGES_REQUESTED** [review]
Date filter left in model

**Review by forgxyz — APPROVED** [review]

**Pull request merged**
